---
# image: gitpod/workspace-full
image:
  file: gitpod.Dockerfile
checkoutLocation: gitpod-k3s
tasks:
  # Force prebuild
  # - init: ./configure && timeout 45m make -j16 || true
  # K3s
  - name: prepare k3s
    command: |
      .gitpod/prepare-k3s.sh
  - name: kernel dev environment
    init: |
      sudo apt update -y
      sudo apt install qemu qemu-system-x86 linux-image-$(uname -r) libguestfs-tools sshpass netcat -y
      sudo curl -o /usr/bin/kubectl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo chmod +x /usr/bin/kubectl
      .gitpod/prepare-rootfs.sh
    command: |
      .gitpod/qemu.sh
  # ENV Variables
  - name: Example of passing an environment variable to a command
    env:
      PRINT_ME: "HelloWorld!"
    command: echo $PRINT_ME
  - name: Start Jupyter
    command: jupyter notebook

# Docker Compose
# - init: |
#     cd docker && docker-compose pull
# - command: |
#     cd docker && docker-compose up
ports:
  - port: 3306
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8888
    onOpen: open-preview
# - port: 3000
#   onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    # - mutantdino.resourcemonitor
    - anwar.resourcemonitor
    - ms-azuretools.vscode-docker
    - ms-python.python
    # - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - redhat.vscode-yaml
    - ms-kubernetes-tools.vscode-kubernetes-tools
    # ARepl for Python: https://www.gitpod.io/docs/languages/python#arepl-for-python
    - almenon.arepl
    # Python Test Explorer
    - littlefoxteam.vscode-python-test-adapter
    # Markdown
    - yzhang.markdown-all-in-one
    # Java
    # - redhat.java
    # - vscjava.vscode-java-debug
    # - vscjava.vscode-java-test
    # - pivotal.vscode-spring-boot

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
